<a href="https://colab.research.google.com/github/R382-ohit/pyTorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import torch
import numpy as np

**Lists**

In [40]:
my_list = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

So this one is a basic python list .

**Numpy arrays**

In [41]:
np1 = np.random.rand(3,4)
np1

array([[0.94903069, 0.65090704, 0.35213983, 0.33909835],
       [0.93091274, 0.91854439, 0.36825876, 0.45732564],
       [0.4541165 , 0.0871847 , 0.89023551, 0.99102584]])

In [42]:
np1.dtype

dtype('float64')

**Tensors**

In [43]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.5347, -0.0015,  1.1024,  0.2303],
        [-0.7075, -0.3611,  1.2825, -0.3884],
        [-0.0797, -0.1718, -0.1071,  1.4665]])

In [44]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [45]:
tensor_3d.type()

'torch.FloatTensor'

In [46]:
tensor_3d.dtype

torch.float32

In [47]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9490, 0.6509, 0.3521, 0.3391],
        [0.9309, 0.9185, 0.3683, 0.4573],
        [0.4541, 0.0872, 0.8902, 0.9910]], dtype=torch.float64)

*Tensor Ops*

In [48]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
## Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [50]:
my_torch = torch.arange(10)
my_torch=my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [51]:
## Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [53]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [54]:
# View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_torch4 = my_torch3.view(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [56]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [68]:
# Slices
my_torch7 = torch.arange(10)
my_torch7[:-1]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# Grab a specific one
my_torch7[6]

tensor(6)

In [66]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [69]:
# Grab a slice S
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])