<a href="https://colab.research.google.com/github/R382-ohit/pyTorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Lists**

In [2]:
my_list = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

So this one is a basic python list .

**Numpy arrays**

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.03174793, 0.70532593, 0.36853503, 0.74805077],
       [0.5904133 , 0.04741803, 0.71128532, 0.35287778],
       [0.00897993, 0.25333456, 0.31809303, 0.24818258]])

In [4]:
np1.dtype

dtype('float64')

**Tensors**

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.6373,  2.3476, -0.3400, -0.8923],
        [ 0.2280, -0.9605, -1.1297, -0.4645],
        [-0.6075,  1.5875,  0.8849,  3.4503]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
tensor_3d.type()

'torch.FloatTensor'

In [8]:
tensor_3d.dtype

torch.float32

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0317, 0.7053, 0.3685, 0.7481],
        [0.5904, 0.0474, 0.7113, 0.3529],
        [0.0090, 0.2533, 0.3181, 0.2482]], dtype=torch.float64)

*Tensor Ops*

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
## Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch = torch.arange(10)
my_torch=my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
## Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [15]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [16]:
# View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch4 = my_torch3.view(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [21]:
# Slices
my_torch7 = torch.arange(10)
my_torch7[:-1]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
# Grab a specific one
my_torch7[6]

tensor(6)

In [23]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
# Grab a slice S
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [25]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

### **Tensor Math Operations<br>**
* Add , Subtract, Multiply , Divide , Remainders , Exponents <br>
* ShortHand and uh , LongHand<br>
* Reassignment<br>

In [26]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [27]:
## Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
# Addition longhand
torch.add(tensor_a,tensor_a)

tensor([2, 4, 6, 8])

In [29]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [30]:
#  LongHand
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [31]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [32]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [33]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [34]:
# LongHand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])