<a href="https://colab.research.google.com/github/R382-ohit/pyTorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Lists**

In [3]:
my_list = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

So this one is a basic python list .

**Numpy arrays**

In [10]:
np1 = np.random.rand(3,4)
np1

array([[0.12508362, 0.08694453, 0.67690483, 0.16091263],
       [0.07625058, 0.73857789, 0.6137016 , 0.18367681],
       [0.45077751, 0.72419551, 0.63558232, 0.49939359]])

In [9]:
np1.dtype

dtype('float64')

**Tensors**

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.3380, -0.0067,  0.0411, -0.0786],
        [-0.1434,  0.3275,  0.2798,  0.8579],
        [ 0.2746,  0.4065, -0.8061, -0.6182]])

In [13]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
tensor_3d.type()

'torch.FloatTensor'

In [15]:
tensor_3d.dtype

torch.float32

In [16]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1251, 0.0869, 0.6769, 0.1609],
        [0.0763, 0.7386, 0.6137, 0.1837],
        [0.4508, 0.7242, 0.6356, 0.4994]], dtype=torch.float64)