<a href="https://colab.research.google.com/github/R382-ohit/pyTorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import torch
import numpy as np

## **Lecture 1**

**Lists**

In [48]:
my_list = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

So this one is a basic python list .

**Numpy arrays**

In [49]:
np1 = np.random.rand(3,4)
np1

array([[0.29494187, 0.40026944, 0.03958203, 0.31453639],
       [0.46330165, 0.59533503, 0.41741451, 0.60213352],
       [0.95833488, 0.30574941, 0.51702508, 0.33882863]])

In [50]:
np1.dtype

dtype('float64')

## **Lecture 2**

**Tensors**

In [51]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.4028, -0.1296,  2.3579, -0.0470],
        [ 0.0994,  1.7806, -0.8204, -1.2818],
        [-1.0364, -0.0520, -0.3521, -0.8003]])

In [52]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [53]:
tensor_3d.type()

'torch.FloatTensor'

In [54]:
tensor_3d.dtype

torch.float32

In [55]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2949, 0.4003, 0.0396, 0.3145],
        [0.4633, 0.5953, 0.4174, 0.6021],
        [0.9583, 0.3057, 0.5170, 0.3388]], dtype=torch.float64)

*Tensor Ops*

## **Lecture 3**

In [56]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
## Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
my_torch = torch.arange(10)
my_torch=my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [59]:
## Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [61]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [62]:
# View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
my_torch4 = my_torch3.view(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [64]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [66]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [67]:
# Slices
my_torch7 = torch.arange(10)
my_torch7[:-1]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
# Grab a specific one
my_torch7[6]

tensor(6)

In [69]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [70]:
# Grab a slice S
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [71]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## **Lecture 4**

### **Tensor Math Operations<br>**
* Add , Subtract, Multiply , Divide , Remainders , Exponents <br>
* ShortHand and uh , LongHand<br>
* Reassignment<br>

In [72]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [73]:
## Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [74]:
# Addition longhand
torch.add(tensor_a,tensor_a)

tensor([2, 4, 6, 8])

In [75]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [76]:
#  LongHand
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [77]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [78]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [79]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [80]:
# LongHand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [81]:
# Remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [82]:
# Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [83]:
# Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [84]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [85]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [86]:
tensor_b.sub(tensor_a)

tensor([4, 4, 4, 4])

In [87]:
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [88]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [91]:
tensor_a.add_(tensor_b)
# this little underscore after add helps in reassignment
# can relate this to the inplace = True thing we used earlier in numpy and pandas

tensor([11, 14, 17, 20])

In [90]:
tensor_a

tensor([ 6,  8, 10, 12])

## **Lecture 5**